before_install: sudo apt-get install lighttpd libfcgi-dev libmemcache-dev memcached
install:
  - gem env version | grep '^\(2\|1.\(8\|9\|[0-9][0-9]\)\)' || gem update --system
  - gem install --conservative rake
  - rake deps
script: rake ci
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx
  - jruby
  - ree
branches:
  # The old 1.1, 1.2, and 1.3 branches aren't correctly setup yet.
  only: master
notifications:
  email: false
  irc: "irc.freenode.org#rack"
matrix:
  allow_failures:
    - rvm: 2.0.0
