before_install:
  - sudo apt-get update > /dev/null
  - sudo apt-get -y install lighttpd libfcgi-dev libmemcache-dev memcached
install:
  - gem env version | grep '^\(2\|1.\(8\|9\|[0-9][0-9]\)\)' || gem update --system
  - bundle install --jobs=3 --retry=3
script: bundle exec rake ci
rvm:
  - 2.2.3
  - 2.3.0
  - ruby-head
  - rbx-2
  - jruby
  - jruby-9.0.4.0
  - jruby-head

notifications:
  email: false
  irc: "irc.freenode.org#rack"

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
