language: ruby
sudo: false
cache:
  - bundler
  - apt

services:
  - memcached

addons:
  apt:
    packages:
      - lighttpd
      - libfcgi-dev

before_install:
  - gem env version | grep '^\(2\|1.\(8\|9\|[0-9][0-9]\)\)' || gem update --system
  - gem list -i bundler || gem install bundler

script: bundle exec rake ci

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head
  - rbx-2
  - jruby-9.0.4.0
  - jruby-head

notifications:
  email: false
  irc: "irc.freenode.org#rack"

matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
